mimetypes:
  text/html: html
  text/markdown: markdown
  text/plain: plain
site:
  baseurl: https://yandex-metrika-goals-example.netlify.app
  language: ru
zas:
  deploy: ../dist/
  layout: ./.zas/layout.html
