# https://taskfile.dev

version: 2

## Common settings
silent: true

tasks:

  build:
    desc: Build by hustie
    cmds:
      - echo "Building to dir {{.OUTDIR}} with url {{.BASEURL}} …"
      - cmd: "hastie"

  clean:
    desc: Cleanup hustie generated files
    cmds:
      - echo "Cleaning caches.."
      - cmd: rm -rf ./dist/
      - cmd: mkdir -p ./dist/

  linkchecker:
    cmds:
      - sleep 2
      - echo "Run link checker after pause ..."
      - cmd: "linkcheck --root http://localhost:{{.PORT}}"
      - echo "-------------------------------------------------------------"
      - echo "Done, plase kill server - Ctrl+C, then Enter"

  links:
    deps:
      - build
      - linkchecker
    cmds:
      - echo Run all together
